name: condatos-figs-app
channels:
  - conda-forge
  - defaults

dependencies:
  # Núcleo
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyyaml
  - typer
  - rich

  # Gráficos
  - matplotlib>=3.10,<3.12
  - seaborn
  - pillow
  - pillow-heif
  - scour

  # Mapas
  - geopandas
  - shapely
  - pyproj
  - fiona
  - mapclassify
  - rtree

  # Exportadores opcionales
  - cairo
  - cairosvg

  # Compresión/soporte extra
  - imageio
  - libwebp

  # Tooling
  - ruff
