template: "templates/barh-condatos.yml"
outfile: "out/condatos-barh"
data:
  inline:
    categories: ["Uruguay","Chile","Costa Rica","Brasil","México"]
    values: [85, 78, 74, 69, 65]
overrides:
  title: "Índice de transparencia (ejemplo)"
  xlabel: "Puntaje"
