template: "templates/heatmap-condatos.yml"
outfile: "out/condatos-heatmap"
data:
  inline:
    rows: ["Chile","Perú","Colombia","México","Argentina"]
    cols: [2020,2021,2022,2023,2024]
    values:
      - [65, 68, 71, 73, 76]
      - [60, 62, 64, 66, 69]
      - [55, 58, 61, 63, 66]
      - [70, 72, 74, 77, 80]
      - [50, 52, 55, 57, 60]
overrides:
  title: "Índice (ejemplo) · países × años"
  xlabel: "Año"
  ylabel: "País"
  annot: true
  fmt: ".0f"
  linewidths: 0.5
  cmap: "magma"
