# Configuración para el índice LATAM
# config/indice-latam.yml
template: templates/choropleth-condatos.yml
outfile: out/indice-latam

# Usa CSV…
data:
  csv: data/indice_latam.csv
  csv_key: iso3        # ← nombre de la columna en el CSV
  value_col: valor     # ← columna con el valor numérico

overrides:
  title: "Índice LATAM"
  subtitle: "Valores de ejemplo"
  scheme: "Quantiles"  # o "NaturalBreaks", "EqualInterval"
  k: 5
  cmap: "YlOrRd"
