template: "templates/line-condatos.yml"
outfile: "out/condatos-linea"
data:
  inline:
    x: [2019,2020,2021,2022,2023,2024]
    y_series:
      Chile:     [100, 98, 105, 110, 113, 118]
      Perú:      [100, 95,  99, 104, 108, 111]
      Colombia:  [100, 97, 103, 109, 114, 120]
overrides:
  title: "Índice base 2019=100 (ejemplo)"
  ylabel: "Índice"
