# /config/medallas-juegos-panamericanos-junior-2025-stacked-horizontal.yml
template: "templates/stackedbar-horizontal-condatos.yml"
outfile: "out/medallas-juegos_panamericanos_junior_2025-stacked-horizontal"
data:
  csv: "data/medallas-juegos-panamericanos-junior-2025.csv"

overrides:      # Calculado: 1.0 - margin_left - margin_right (1.0 - 0.22 - 0.12)
  title:
    text: "Medallas por país – Juegos Panamericanos Junior Asunción 2025"
    wrap: true         # Habilitar wrapping dentro del ancho definido
  
  subtitle:
    text: "Total de preseas ganadas (oro, plata y bronce) en los Juegos Panamericanos Junior."
    wrap: true         # Habilitar wrapping dentro del ancho definido

  # # Layout - definiendo explícitamente los márgenes
  # layout:
  #   margin_left: 0.22    # espacio para etiquetas Y
  #   margin_right: 0.12   # espacio para banderas/totales
  #   margin_top: 0.15     # espacio para el header
  #   margin_bottom: 0.15  # espacio para el footer

  # Resto de la configuración igual...
  branding:
    source: "Pagina oficial de los Juegos Panamericanos Junior Asunción 2025, https://www.asu2025.org.py/"
    note: "Licencia CC BY-NC-SA 4.0"
    date_auto: true
    icons: ["assets/cc.png", "assets/by.png", "assets/nc.png"]
    logo: "assets/logo_condatos.png"
  
  category_col: "pais"
  series_order: ["oro", "plata", "bronce"]
  dpi: 300

  colors:
    oro: "#B6862C"
    plata: "#7D7D7D"
    bronce: "#8C5A2B"
  