# Configuración para visualización de inflación y PIB
# Nombre: pib-inflacion-linechart.yml

# Usar el template de gráfico de líneas
template: "templates/linechart-condatos.yml"

# Personalizar el título y subtítulo para este gráfico específico
title: "Evolución del PIB e Inflación en Chile"
subtitle: "Datos trimestrales (2015-2023)"

# Datos de ejemplo (inline) - Simular los datos de la consulta SQL
data:
  inline:
    fecha_trimestre: [
      "2015-03", "2015-06", "2015-09", "2015-12",
      "2016-03", "2016-06", "2016-09", "2016-12",
      "2017-03", "2017-06", "2017-09", "2017-12",
      "2018-03", "2018-06", "2018-09", "2018-12",
      "2019-03", "2019-06", "2019-09", "2019-12",
      "2020-03", "2020-06", "2020-09", "2020-12",
      "2021-03", "2021-06", "2021-09", "2021-12",
      "2022-03", "2022-06", "2022-09", "2022-12",
      "2023-03", "2023-06", "2023-09", "2023-12"
    ]
    pib_var_trimestral: [
      1.8, 2.1, 2.4, 1.9,
      1.3, 0.9, 1.2, 1.5,
      1.7, 2.2, 2.5, 2.8,
      3.1, 3.5, 2.9, 2.6,
      2.3, 2.0, 1.8, 1.5,
      -0.7, -12.5, -8.1, -2.8,
      0.5, 17.2, 10.8, 7.1,
      5.2, 2.8, 1.1, -0.5,
      -0.2, 0.3, 0.6, 0.9
    ]
    inflacion_trimestral: [
      4.1, 3.8, 4.2, 4.4,
      4.6, 4.2, 3.9, 3.5,
      3.1, 2.8, 2.5, 2.3,
      2.1, 2.4, 2.6, 2.9,
      3.0, 2.8, 2.5, 2.7,
      3.2, 2.5, 3.0, 3.5,
      3.8, 4.2, 5.5, 6.8,
      8.5, 11.2, 12.8, 12.5,
      11.8, 8.5, 5.7, 4.2
    ]

# Configuración del mapeo de columnas
data_source:
  column_mapping:
    x: "fecha_trimestre"
    series:
      - name: "Variación PIB (%)"
        column: "pib_var_trimestral"
        color: "#1A535C"
      - name: "Inflación (%)"
        column: "inflacion_trimestral"
        color: "#FF6B6B"

# Personalizar aspectos visuales específicos para este gráfico
linechart:
  linewidth: 3
  marker:
    enabled: true
    size: 7
    edgewidth: 1.5

# Destacar áreas de interés en el gráfico
annotations:
  regions:
    - label: "Pandemia COVID-19"
      from: "2020-03"
      to: "2021-06"
      color: "#f8f8f8"
      alpha: 0.3

# Personalizar etiquetas de valores para este gráfico
value_labels:
  show: true
  format: "{:.1f}%"
  fontsize: 9
  only_last: true
  background: true
  bg_alpha: 0.8

# Configuración de los ejes
xaxis:
  title: "Trimestre"
  title_fontsize: 12
  title_fontweight: "bold"

yaxis:
  title: "Porcentaje (%)"
  title_fontsize: 12
  title_fontweight: "bold"

# Configuración de la leyenda
legend_config:
  loc: "upper right"
  fontsize: 11
  frameon: true
  facecolor: "#ffffff"
  framealpha: 0.9
  fancybox: true

# Personalizar la fuente para este gráfico específico
footer:
  source: "Fuente: Banco Central de Chile, 2023"